### ISSUE TITLE
In code config overrides config file

### ISSUE THREAD

**Issue by Kasprenius** [SFort/MC-betterbeacon#3]
I cant change the value for per block boost because you have it set up to a default.

**Comment by SFort** [comment]
my configs usually reset the value if there is a parsing error so any chance a id was misspelled?

**Comment by SFort** [comment]
please send the config you are atempting to apply

**Comment by Kasprenius** [comment]
10.0
^-Beacon: Default range  [10.0] 0.0 - ...
10.0
^-Beacon: Added range per level  [10.0] 0.0 - ...
minecraft:iron_block;0.0;minecraft:gold_block;0.0;minecraft:diamond_block;0.5;minecraft:emerald_block;0.5;minecraft:netherite_block;1.0
^-Beacon: Added range per block of type [minecraft:iron_block;0.0;minecraft:gold_block;0.0;minecraft:diamond_block;0.5;minecraft:emerald_block;0.5;minecraft:netherite_block;2.0] ID;AMOUNT;...
true
^-Conduit: Add vanilla range [true] true | false

^-Conduit: Added range per block of type [] ID;AMOUNT;...
null

**Comment by Kasprenius** [comment]
Whenever i change any of the values in the per block of type it resets the line.

**Comment by Kasprenius** [comment]
Also, off topic but the beacon overhaul mod seems to override your ranges DX

**Comment by SFort** [comment]
so as far as i can see the only thing you changed is netherite_block;2.0 to netherite_block;1.0

which is working when i test it
(although havent tested on older versions so if you're using one do say)

(i'll take a look at beacon overhaul)

**Comment by Kasprenius** [comment]
yes but you see when I try to change the second netherite value from 2 to 1 or any of the second values for that matter it resets

**Comment by SFort** [comment]
running v1.0.5 on 1.17?

**Comment by Kasprenius** [comment]
yep!

**Comment by SFort** [comment]
[file redacted]
I'm outa ideas why this would happen soo, try that see if it crashes
if it does send log, ty

**Comment by Kasprenius** [comment]
didn't crash but also still changed the values back

**Comment by SFort** [comment]
so if you open up the logs there's nothing along the lines of :  
"tf.ssf.sfort.beaconbalance failed to load config" .....
followed by a crash?

**Comment by SFort** [comment]
also while you're at it mightaswell send the log just in case there's something usefull in it

**Comment by Kasprenius** [comment]
[latest.log](https://github.com/SFort/MC-betterbeacon/files/7232204/latest.log)

**Comment by SFort** [comment]
well um there are a lot of errors but none of them related

try replacing the config with mine just in case it's your text editor?
[conf.zip](https://github.com/SFort/MC-betterbeacon/files/7232224/conf.zip)

**Comment by SFort** [comment]
Few tests later i still have no clue what's causing this

> Also, off topic but the beacon overhaul mod seems to override your ranges DX

but at least that is getting fixed

**Comment by SFort** [comment]
I'm assuming it was the text editor inserting wierd spacing. in which case oh well will get fixed if i ever decide on a proper config format
