### ISSUE TITLE
Edited Config does NOT match results in game

### ISSUE THREAD

**Issue by AspieGamer13** [SFort/MC-betterbeacon#4]
First, my config:
`12.0`
`^-Beacon: Default range  [10.0] 0.0 - ...`
`12.0`
`^-Beacon: Added range per level  [10.0] 0.0 - ...`
`minecraft:iron_block;0.25;minecraft:gold_block;0.25;minecraft:diamond_block;0.5;minecraft:emerald_block;0.5;minecraft:netherite_block;1.0`
`^-Beacon: Added range per block of type [minecraft:iron_block;0.0;minecraft:gold_block;0.0;minecraft:diamond_block;0.5;minecraft:emerald_block;0.5;minecraft:netherite_block;2.0] ID;AMOUNT;...`
`false`
`^-Conduit: Add vanilla range [true] true | false`
`minecraft:prismarine;2.5;minecraft:dark_prismarine;2.5;minecraft:prismarine_bricks;2.5;minecraft:sea_lantern;2.5`
`^-Conduit: Added range per block of type [] ID;AMOUNT;...`
`null`

This is version 1.18.1, and it seems that with no changes, everything works as expected based on the defaults. I used Notepad++ to edit, which I seriously doubt could be a cause for the following issues.

With the beacons, what I expect is a range of 12 blocks + 12 blocks per layer + (0.25/0.5/1.0) * number of block in beacon. What I get, for every single beacon size and material, is 12 blocks + 12 blocks per layer.

With the conduits, what I expect is 16 blocks minimum to activate and a range of 2.5 * number of blocks in frame. What I get is 8 blocks minimum to activate and a range of ¯\_(ツ)_/¯.

- At 8 blocks, I expect a range of 20 and get a range of 31.
- At 16 blocks, I expect a range of 48 and get a range of 63.
- At the full 42 blocks, I expect a range of 105 and get a range of 167.

It seems this range is 4 * number of blocks in frame - 1, but when I tried with a value of 3.0 I got ranges of 6 * number of blocks in frame.

**Comment by SFort** [comment]
the conduit thing is deffinatly a bug.
so adding already valid conduit block makes it counts twice

as for the beacon range per block not working that i cannot reproduce. probably the fault of the config being jank so i'm counting it as a +1 on my mods __need__ a config overhaul

**Comment by AspieGamer13** [comment]
In the meantime, I'm going for a simplified version with the beacons: ? blocks range + ? blocks range per level, no block bonus (probably 20 or 25 blocks).

As for the conduit, I'll just let that stay default for now.

It's not my desired customization settings, but it'll do.

(Also, unsure what that last null is in the config?)

**Comment by SFort** [comment]
that is a result of me a year ago or so being undecicive; not picking a proper config format.
deciding fuck it let's just have every other line be a value. and never fixing it 
(mostly because i still can't decide if i should change to a better config format 
and because the null dosn't cause any issues)

also i've fixed the conduit issue just testing to make sure should be out soon

**Comment by SFort** [comment]
[1.0.6](https://github.com/SFort/MC-betterbeacon/releases/tag/r1.0.6) should resolve the conduit issue

**Comment by SFort** [comment]
as for the beacon do you have any mods that might be conflicting?

**Comment by AspieGamer13** [comment]
I have no clue. None of the mods I have, except this, directly deal with the beacon (or indirectly afaik)

Other Mods:
- Apple Skin
- Architectury
- Auth Me
- Carpet
- Carpet Extra
- Carpet Fixes
- Cloth
- Dynmap
- Entity Culling
- Fabric API
- Horse Stats Vanilla
- Iris
- Light Overlay
- Litematica
- Lithium
- MaLiLib
- Mini Hud
- Mini Tweaks (Carpet)
- Shulker Box Tooltip
- Sodium
- Starlight
- Terralith

PS: Iris was installed after this issue, so it can't be the cause; The Carpet family of mods did not have anything running to change anything (they were just sitting there in the background), so it's unlikely they would have caused an issue.
PPS: For my server, Fabric API, MaLiLib, Architectury & Cloth are required; Lithium & Starlight (and eventually Hydrogen) will be used for performance; Carpet, Carpet Extra, Carpet Fixes & Mini Tweaks will be used to enhance vanilla gameplay, as well as Better Beacon; Terralith will be used for custom biomes; Apple Skin will be used to send accurate hunger information to clients running same mod; and Dynmap for server map. All other mods will be client side, all server side mods chosen to allow completely unmodded clients to join.

**Comment by SFort** [comment]
add `-Dmixin.debug.export=true`
to the java parameters start the pack you're using and send me `.minecraft/.mixin.out/class/net/minecraft/class_2580.class` and `class_2238` as it's going to be a lot quicker then me checking all those mods

**Comment by AspieGamer13** [comment]
I don't see a class_2238 file
Here is the other file:

edit by sfort: i removed the file url as looking back i'm not sure if sending decompiled classes is allowed

**Comment by SFort** [comment]
the only other mod making changes to the beacon seames to me "fi.dy.masa.minihud"

**Comment by SFort** [comment]
but as far as i can tell it's not conflicting so the only likely option is the values aren't getting loaded

**Comment by SFort** [comment]
(also for educational purposes if you don't see a file in .mixin.out when exporting debug mixins it means no mod changed that file)

**Comment by AspieGamer13** [comment]
I ran a test without that mod and it literally made no difference in the outcome. I am continuing to run tests to see if anything works. I've just deleted the config so it loads a fresh one.

**Comment by AspieGamer13** [comment]
weirdly, the config for the beacon works in one world, but not in another (superflat).
also, the config for the conduit doesn't seem to be taking the decimal number (and it seems to be subtracting 1 or 2 from the end distance). Ex: 3.5 in config, expect 3.5 * no/blocks, get 3 * no/blocks - 1 or 2.

**Comment by SFort** [comment]
~i can make that a bit better but only to an extent as~ 
minecraft for some reason stores it without decimals
edit: turns out not really viable would require too much hacky code

**Comment by AspieGamer13** [comment]
A tossup if the beacon will work and whole numbers only for conduits 👍🏻

If, after I get back from vacation, when I get my server up and running and have issues with beacons not working properly, I'll say something here.
I'll just live with the conduit modifications as is since it's beyond your control, and at least I can make any change to it.

**Comment by SFort** [comment]
after reading this again think i figured it out, 1.18 added negative Y cordinates and flat worlds stard you in the negative coords
