### ISSUE TITLE
Config reset

### ISSUE THREAD

**Issue by MOOOOs** [SFort/MC-betterbeacon#5]
Hey i have problem for some unknown reason config resets "Beacon: Added range per block" values when "Beacon: Added range per level" being kept as i edited when i launch Minecraft 1.19.2. I only changed digits didn't move any other symbol i also got Beacon Overhaul mod but i have read that it's compatible idk why this is caused please help what I'm doing wrong.
Here is full config after it resets when game is launched.
10.0
^-Beacon: Default range  [10.0] 0.0 - ...
10.0
^-Beacon: Added range per level  [10.0] 0.0 - ...
minecraft:gold_block;1.5;minecraft:iron_block;1.0;minecraft:diamond_block;2.0;minecraft:netherite_block;5.0;minecraft:emerald_block;2.5
^-Beacon: Added range per block of type [minecraft:iron_block;0.0;minecraft:gold_block;0.0;minecraft:diamond_block;0.5;minecraft:emerald_block;0.5;minecraft:netherite_block;2.0] ID;AMOUNT;...
true
^-Conduit: Add vanilla range [true] true | false

^-Conduit: Added range per block of type [] ID;AMOUNT;...
null

**Comment by SFort** [comment]
"Added range per block of type" config shuffles the values on every launch
so it might be shuffling `iron_block;1.0;gold_block;2.0` to `gold_block;2.0;iron_block;1.0`

if it's reseting the value, edit the config send it as an attachment, startup minecraft close it afther it loads and also send `.minecraft/logs/latest.log` as an attachment
(just drag and drop into the comment window)

**Comment by MOOOOs** [comment]
It only shuffles Beacon: Added range per level but every range as i calculated works correctly so its not problem i guess. Only Beacon: Added range per block of type reseting here is config with edited values and log put it into zip because github doesn't support conf file type
[Config and log.zip](https://github.com/SFort/MC-betterbeacon/files/9548562/Config.and.log.zip)

**Comment by SFort** [comment]
i really need to decide on a proper config format one of these days.

will try to remember to fix this with the next version
(likely to be a while, betterbeacon dosn't get frequest updates)

**Comment by MOOOOs** [comment]
i guess then i only use Added range per level then

**Comment by SFort** [comment]
oh wait i missread that so it _does_ actually reset added range per block, i'll try n see why then

**Comment by SFort** [comment]
so the configs for my mods currently work in the following way:
1st line: value
2nd line: comment
3rd line: value
4th line: comment

etc. repeats

![screenshot](https://user-images.githubusercontent.com/1879846/189679517-205cb710-9ff9-4ec0-9d3d-453b07d73e4d.png)

noticed you edited both the value and the comment that tells you what the default value is.
just making sure that this isn't just my poorly made config being confusing.
the actuall value on line 4 is reseting?

**Comment by MOOOOs** [comment]
interesting so if i  edit value then it also changes beacon added range per block too?
for example netherite per level will be 10x5 and per block type 10x5 too? also getting 150 range now with this same config line 5 resets 
i guess its not bug then just confusion

**Comment by MOOOOs** [comment]
also why i get 150 range from beacon can i get how it calculates range? because i only count 10+50+50=110 if this is correct

**Comment by SFort** [comment]
https://www.curseforge.com/minecraft/mc-mods/better-beacon#c23

>all of the numbers in the config refer to the range of the beacon
for example
>
>9.0
>^-Beacon: Default range
>10.0
>^-Beacon: Added range per level
>minecraft:iron_block;1.0;minecraft:gold_block;2.0
>^-Beacon: Added range per block of type
>
>
>means that the beacon will have a range of 9 + ( 10 * level ) + (1 * count of iron blocks in the beacon) + (2 * count of gold blocks in the beacon)
>
>so if someone made a level 1 beacon with iron blocks that would mean 9 + ( 10 * 1 ) + (1 * 9) + ( 2 * 0)
>
>and the beacon would have a range of 28 blocks (or 37 if gold was used)

**Comment by MOOOOs** [comment]
then i should have 870 range if this is correct formula 10+ (10x4) + (5x164) i guess 150 is limit of beacon range

**Comment by SFort** [comment]
~a full netherite level 4 beacon should have a range of 1270 blocks with the config you sent 
`10 + (10 * 4) + (244 * 5) = 1270`~ nvm i got the amount of becon blocks wrong
i'm guessing you might be outside simulation/render range and the beacon has become unloaded?

you can probably test that with the `/forceload` command or a nether portal chunk loader

**Comment by MOOOOs** [comment]
why i calculated that its only 164 blocks (9x9)+(7x7)+(5x5)+(3x3)=81+49+25+9=164

**Comment by SFort** [comment]
ye i just went to the wiki and pulled the number for _multiple_ beacons instead of the correct one you used

**Comment by MOOOOs** [comment]
i don't know forceload doesn't work its not command that exist in minecraft

**Comment by SFort** [comment]
https://minecraft.fandom.com/wiki/Commands/forceload

**Comment by MOOOOs** [comment]
oh its in game settings that limit its range simulation distance :) thanks for the help i guess default settings is more than enough i need about 200/250 range
